### ISSUE TITLE
5vs5 instead if 1vs1vs1..vs1?

### ISSUE THREAD

**Issue by Whyser** [Kjagd/dotarun#101]
Hello! Really like your DOTA Run! Would it be an easy-fix to make it so that there is two teams instead of Free-for-All? @Kjagd

**Comment by Kjagd** [comment]
Hey @Whyser and thanks :)! Yes it would be possible, however we decided not to do so, since it would require two maps and therefore dilute the playerbase.

**Comment by Whyser** [comment]
It would not be possible for players to vote when already in-game (like in-game playerime), so they are assigned teams runtime?

**Comment by Kjagd** [comment]
Since 7.00 it is pretty difficult to do due to the pop-up hero selection stuff. It might be possible to do it in-game somehow, but not in an easy way. When the game is loaded, it's not easy to reassign player teams.
