### ISSUE TITLE
Ice Path has no effect

### ISSUE THREAD

**Issue by Gablekkecret** [Kjagd/dotarun#111]
Dear Developer,

Kindly need your help to fix bugs related to Skill Ice path (2nd skill Jakiro) has no freeze effect. 

Best regards,
Tama

**Comment by mathiastj** [comment]
Ice Path changed in 7.32 so probably hasn't worked since:
https://dota2.fandom.com/wiki/Jakiro/Changelogs

**Comment by mathiastj** [comment]
The modifier name has changed from `duration` to `stun_duration`
https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/npc_abilities.txt
vs
https://github.com/Kjagd/dotarun/blob/master/game/dota_addons/dotarun/scripts/npc/npc_abilities_custom.txt

Might want to add `path_duration` as well.
