### ISSUE TITLE
Unplayable

### ISSUE THREAD

**Issue by razeluxe6** [Kjagd/dotarun#118]
Hero becomes immune and can't move when you use hook and the other skills doesn't work too like Pit of Malice, etc. Manta style also gives 2 illu instead of 1
![bug](https://github.com/user-attachments/assets/0c10d5d3-8d56-4c7e-b238-867b5134729c)

**Comment by mathiastj** [comment]
Fixed in https://github.com/Kjagd/dotarun/commit/ee4fbc242a15abc3d268de504266687e6ddc4e07
