### ISSUE TITLE
Replace rocket with charging spirit breaker

### ISSUE THREAD

**Issue by okokookokok** [Kjagd/dotarun#89]
Charging spirit breaker should spawn a spirit breaker when you click the spell which targets perhaps first number 4,3,2 then 1 or just goes for number one.
Probably hard to update the target if people change positions

**Comment by Kjagd** [comment]
Why is this better than missile?

**Comment by okokookokok** [comment]
Because it hits everyone else in it's path as well!
And it looks a lot more fun.

We can also have both

**Comment by okokookokok** [comment]
Needs a tooltip too
