### ISSUE TITLE
Kotl error

### ISSUE THREAD

**Issue by okokookokok** [Kjagd/dotarun#90]
He can only get 3 spells often
Probably just remove him now that Underlord is in

**Comment by Kjagd** [comment]
Strange, any reason for this o.O?

**Comment by okokookokok** [comment]
Dunno, der står bare han er full selvom han har 3 empty abilities

**Comment by Kjagd** [comment]
Han er vel senil..

**Comment by okokookokok** [comment]
Han er blevet slettet, heh.
