### ISSUE TITLE
7.00

### ISSUE THREAD

**Issue by okokookokok** [Kjagd/dotarun#92]
So far it seems like it only broke our way of adding abilities.

We get to "[   00:03:11.749 VScript ]: Hero already has six abilities" when they are all the empty ability.

**Comment by okokookokok** [comment]
Probably line 35 and onwards of dotarun.lua

Oh it also just crashed with: [ W 00:05:03.817 Entity System          ]: Cannot create an entity because entity class is NULL -1

**Comment by Kjagd** [comment]
I crashed in round 2 when picking up stuff. (same message as above)

**Comment by Kjagd** [comment]
Ability indexes are shifted since the talens are on index 1-8. So looping 9 to 14 works, but I can't cast them "Ability not learned"
