### ISSUE TITLE
Recharge skills and items too fast

### ISSUE THREAD

**Issue by Mexmen** [Kjagd/dotarun#93]
Please increase the cooldown of the skills and items, one can not play quietly without 2 or 3 rats trying to fuck you so that you do not win definitively in all the rounds.

**Comment by okokookokok** [comment]
Do you mean the cooldown such that you need to wait longer when walking over the squares to get new spells and items?

What is the problem exactly? Are some people not playing to win but simply camping randoms squares and then shooting everything on people when they come by?

We can look into increasing the cooldown between getting skills and items from the same square.
